export const REQUEST_ADMIN_DATA_LOAD = "REQUEST_ADMIN_DATA_LOAD";
export const RECIVED_ADMIN_DATA_LOAD = "RECIVED_ADMIN_DATA_LOAD";
export const SUCCESS_NOTICE = "SUCCESS_NOTICE";
export const ERROR_NOTICE = "ERROR_NOTICE";
export const WARNING_NOTICE = "WARNING_NOTICE";
export const REMOVE_NOTICE = "REMOVE_NOTICE";
export const LOCATION_CHANGE = "LOCATION_CHANGE";
export const NOTICE_CREATE = "NOTICE_CREATE";
export const NOTICE_REMOVE = "NOTICE_REMOVE";

